const About = () => {
    return ( 
        <div className="about">
            <h1>About Cryptic</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi cupiditate aliquam voluptate eligendi sequi corrupti velit rem. Atque placeat perferendis, temporibus harum numquam deserunt distinctio autem repudiandae, iure facere doloremque blanditiis maiores. Ex similique reiciendis accusamus delectus molestiae? Accusamus nemo adipisci voluptatum cupiditate est accusantium natus hic quo porro assumenda, voluptates labore aliquid odit repudiandae tenetur repellat maxime illum iure praesentium pariatur eius consequatur quam modi velit. Deserunt quasi quisquam fugit debitis sint ut laudantium hic, voluptates deleniti cumque sit quod voluptatum vero animi voluptatibus numquam perspiciatis nesciunt sequi impedit eaque minus eum. Minima architecto fugit dolore expedita officia inventore?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi cupiditate aliquam voluptate eligendi sequi corrupti velit rem. Atque placeat perferendis, temporibus harum numquam deserunt distinctio autem repudiandae, iure facere doloremque blanditiis maiores. Ex similique reiciendis accusamus delectus molestiae? Accusamus nemo adipisci voluptatum cupiditate est accusantium natus hic quo porro assumenda, voluptates labore aliquid odit repudiandae tenetur repellat maxime illum iure praesentium pariatur eius consequatur quam modi velit. Deserunt quasi quisquam fugit debitis sint ut laudantium hic, voluptates deleniti cumque sit quod voluptatum vero animi voluptatibus numquam perspiciatis nesciunt sequi impedit eaque minus eum. Minima architecto fugit dolore expedita officia inventore?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi cupiditate aliquam voluptate eligendi sequi corrupti velit rem. Atque placeat perferendis, temporibus harum numquam deserunt distinctio autem repudiandae, iure facere doloremque blanditiis maiores. Ex similique reiciendis accusamus delectus molestiae? Accusamus nemo adipisci voluptatum cupiditate est accusantium natus hic quo porro assumenda, voluptates labore aliquid odit repudiandae tenetur repellat maxime illum iure praesentium pariatur eius consequatur quam modi velit. Deserunt quasi quisquam fugit debitis sint ut laudantium hic, voluptates deleniti cumque sit quod voluptatum vero animi voluptatibus numquam perspiciatis nesciunt sequi impedit eaque minus eum. Minima architecto fugit dolore expedita officia inventore?</p>
        </div>
     );
}
 
export default About;